include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-raw-types: true
  errors:
    require_trailing_commas: error
    avoid_redundant_argument_values: error
    unnecessary_overrides: error
    dead_code: info
    must_be_immutable: ignore
    strict_raw_type: ignore

linter:
  rules:
    avoid_redundant_argument_values: true
    avoid_init_to_null: true
    avoid_print: true
    constant_identifier_names: true
    file_names: true
    non_constant_identifier_names: true
    null_check_on_nullable_type_parameter: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_is_empty: true
    prefer_null_aware_operators: true
    sized_box_for_whitespace: true
    unnecessary_brace_in_string_interps: true
    always_use_package_imports: true
    always_put_required_named_parameters_first: false
    sort_pub_dependencies: false
    prefer_if_elements_to_conditional_expressions: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
