name: level_up_life
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  dio_request_inspector: ^3.1.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_it: ^8.0.2
  intl: ^0.19.0
  mocktail: ^1.0.4
  logger: ^2.5.0
  slang: ^4.1.0
  slang_flutter: ^4.1.0
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  toastification: ^2.3.0
  nylo_framework: ^6.4.4
  objectbox: ^4.0.3
  objectbox_flutter_libs: ^4.0.3
  path_provider: ^2.1.5
  path: ^1.9.0
  uuid: ^4.5.1
  supabase: ^2.6.1
  connectivity_plus: ^6.1.1
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  change_app_package_name: ^1.4.0
  flutter_lints: ^3.0.0
  objectbox_generator: ^4.0.3

objectbox:
  output_dir: data/services/database/objectbox

flutter:
  uses-material-design: true
  assets:
    - lib/presentation/flavor/env/
    - resources/i18n/